export const FETCH_CONVERSATIONS = "FETCH_CONVERSATIONS";
export const UPDATE_CONVERSATION = "UPDATE_CONVERSATION";
export const HIGHLIGHT_CONVERSATION = "HIGHLIGHT_CONVERSATION";
export const CREATE_CONVERSATION = "CREATE_CONVERSATION";
